[package]
name = "torch"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keccak = "0.1.4"
uint = "0.9.5"
log = "0.4.20"
